"""Словари марок и моделей для валидации поля car."""

# canonical -> [aliases]
BRAND_ALIAS_GROUPS: list[tuple[str, list[str]]] = [
    # --- Массовые мировые ---
    ("Toyota", ["toyota", "тойота", "тоёта", "тайота"]),
    ("BMW", ["bmw", "бмв", "бмдаблювей", "бэха", "бэху"]),
    ("Mercedes", ["mercedes", "mercedes-benz", "mercedes benz", "мерседес", "мерс", "мерин", "мерседес-бенц"]),
    ("Audi", ["audi", "ауди"]),
    ("Lexus", ["lexus", "лексус"]),
    ("Honda", ["honda", "хонда"]),
    ("Nissan", ["nissan", "ниссан"]),
    ("Ford", ["ford", "форд"]),
    ("Chevrolet", ["chevrolet", "шевроле", "chevy", "шеви"]),
    ("Volkswagen", ["volkswagen", "vw", "фольксваген", "фв", "волkswagen"]),
    ("Hyundai", ["hyundai", "хендай", "хюндай", "хёндай", "хундай", "хендэ"]),
    ("Kia", ["kia", "киа", "кия"]),
    ("Mazda", ["mazda", "мазда"]),
    ("Subaru", ["subaru", "субару"]),
    ("Volvo", ["volvo", "вольво"]),
    ("Porsche", ["porsche", "порше", "порш"]),
    ("Land Rover", ["land rover", "landrover", "ленд ровер", "лендровер"]),
    ("Range Rover", ["range rover", "rangerover", "рендж ровер", "рейндж ровер", "рэнж ровер"]),
    ("Jeep", ["jeep", "джип"]),
    ("Tesla", ["tesla", "тесла"]),
    ("Mitsubishi", ["mitsubishi", "мицубиси", "мицубиши"]),
    ("Suzuki", ["suzuki", "сузуки"]),
    ("Isuzu", ["isuzu", "исузу"]),
    ("Daihatsu", ["daihatsu", "дайхатсу"]),
    ("Infiniti", ["infiniti", "инфинити"]),
    ("Acura", ["acura", "акура"]),
    ("Genesis", ["genesis", "генезис"]),
    ("Datsun", ["datsun", "датсун"]),
    # --- Премиум / спорт ---
    ("Ferrari", ["ferrari", "феррари"]),
    ("Lamborghini", ["lamborghini", "ламборгини", "ламба"]),
    ("Maserati", ["maserati", "мазерати"]),
    ("Bentley", ["bentley", "бентли"]),
    ("Rolls-Royce", ["rolls-royce", "rolls royce", "rollsroyce", "роллс-ройс", "роллс ройс"]),
    ("Aston Martin", ["aston martin", "astonmartin", "астон мартин"]),
    ("Bugatti", ["bugatti", "бугатти"]),
    ("McLaren", ["mclaren", "макларен", "макларэн"]),
    ("Pagani", ["pagani", "пагани"]),
    ("Koenigsegg", ["koenigsegg", "кенигсег", "кёнигсегг"]),
    ("Maybach", ["maybach", "майбах"]),
    ("Alpine", ["alpine", "альпин"]),
    ("Lotus", ["lotus", "лотус"]),
    ("Rimac", ["rimac", "римак"]),
    ("Lucid", ["lucid", "люсид"]),
    ("Rivian", ["rivian", "ривиан"]),
    ("Polestar", ["polestar", "полестар", "полстар"]),
    # --- Европейские массовые ---
    ("Renault", ["renault", "рено"]),
    ("Peugeot", ["peugeot", "пежо"]),
    ("Citroen", ["citroen", "citroën", "ситроен"]),
    ("Opel", ["opel", "опель"]),
    ("Skoda", ["skoda", "шкода", "škoda"]),
    ("Seat", ["seat", "сеат", "сиат"]),
    ("Cupra", ["cupra", "купра"]),
    ("Fiat", ["fiat", "фиат"]),
    ("Alfa Romeo", ["alfa romeo", "alfaromeo", "alfa", "альфа ромео", "альфа"]),
    ("Lancia", ["lancia", "ланча"]),
    ("Abarth", ["abarth", "абарт"]),
    ("Dacia", ["dacia", "дачия", "дача"]),
    ("Saab", ["saab", "сааб"]),
    ("Smart", ["smart", "смарт"]),
    ("Mini", ["mini", "мини"]),
    ("Jaguar", ["jaguar", "ягуар"]),
    ("DS", ["ds automobiles", "ds", "дс", "дс автомобилс"]),
    ("Vauxhall", ["vauxhall", "воксхолл"]),
    ("Rover", ["rover", "ровер"]),
    # --- Американские ---
    ("Cadillac", ["cadillac", "кадиллак", "кадик"]),
    ("Lincoln", ["lincoln", "линкольн"]),
    ("Buick", ["buick", "бьюик"]),
    ("GMC", ["gmc", "джиэмси"]),
    ("Dodge", ["dodge", "додж"]),
    ("Chrysler", ["chrysler", "крайслер"]),
    ("Ram", ["ram", "рам", "ram trucks", "рэм"]),
    ("Hummer", ["hummer", "хаммер", "хамер"]),
    ("Pontiac", ["pontiac", "понтиак"]),
    ("Mercury", ["mercury", "меркюри"]),
    ("Oldsmobile", ["oldsmobile", "олдсмобиль"]),
    ("Saturn", ["saturn", "сатурн"]),
    ("Scion", ["scion", "сцион", "скайон"]),
    # --- Китайские ---
    ("BYD", ["byd", "бивайди", "бюд", "биуайди"]),
    ("Geely", ["geely", "джили", "гили", "жили"]),
    ("Great Wall", ["great wall", "greatwall", "грет вол", "грейт вол"]),
    ("Haval", ["haval", "хавал", "хавейл"]),
    ("Chery", ["chery", "чери", "черри"]),
    ("Exeed", ["exeed", "эксид", "ексид"]),
    ("Omoda", ["omoda", "омода"]),
    ("Jaecoo", ["jaecoo", "джеку", "жаеку", "жаку"]),
    ("Changan", ["changan", "чанган"]),
    ("Dongfeng", ["dongfeng", "донгфенг"]),
    ("Foton", ["foton", "фотон"]),
    ("GAC", ["gac", "гак", "гуанчжоу"]),
    ("Hongqi", ["hongqi", "хонги", "хунци", "хунци"]),
    ("Li Auto", ["li auto", "lixiang", "ли авто", "лисян"]),
    ("NIO", ["nio", "нио"]),
    ("Xpeng", ["xpeng", "ксяпенг", "икспенг", "сяопэн"]),
    ("Zeekr", ["zeekr", "зикр", "зикер"]),
    ("AITO", ["aito", "айто"]),
    ("Leapmotor", ["leapmotor", "липмотор", "липмотор"]),
    ("WM Motor", ["wm motor", "wm", "вм мотор", "weltmeister", "вельтмайстер"]),
    ("Voyah", ["voyah", "воя", "воях"]),
    ("Seres", ["seres", "серес"]),
    ("Skyworth", ["skyworth", "скайворт"]),
    ("MG", ["mg", "эмджи", "мг"]),
    ("Tank", ["tank", "танк"]),
    ("Jetour", ["jetour", "джетур"]),
    ("Baic", ["baic", "баик", "бейц", "beijing"]),
    ("JAC", ["jac", "джак", "жак"]),
    ("Lifan", ["lifan", "лифан"]),
    ("Zotye", ["zotye", "зоти", "зотей"]),
    ("Maxus", ["maxus", "максус"]),
    ("Roewe", ["roewe", "роув", "рове"]),
    ("Wuling", ["wuling", "вулинг"]),
    ("Deepal", ["deepal", "дипал"]),
    ("Avatr", ["avatr", "аватр"]),
    ("ORA", ["ora", "ора"]),
    ("WEY", ["wey", "вей", "вэй"]),
    ("Bestune", ["bestune", "бестюн", "бестурн"]),
    ("FAW", ["faw", "фав", "фао"]),
    ("Arcfox", ["arcfox", "аркфокс"]),
    ("Lynk & Co", ["lynk & co", "lynk co", "lynk", "линк ко", "линк"]),
    ("Soueast", ["soueast", "соуист", "суист"]),
    ("Haima", ["haima", "хаима"]),
    # --- Китайские (дополнительные, популярные) ---
    ("Aion", ["aion", "айон", "эон", "гак айон"]),
    ("Xiaomi", ["xiaomi", "сяоми", "ксяоми", "шаоми"]),
    ("Denza", ["denza", "дэнза", "денза"]),
    ("HiPhi", ["hiphi", "хифи", "хаифи"]),
    ("GAC Trumpchi", ["gac trumpchi", "trumpchi", "трампчи", "транчи", "гуанчи"]),
    ("Baojun", ["baojun", "баоджун", "баоцзюнь"]),
    ("iCar", ["icar", "айкар", "икар"]),
    ("Hozon", ["hozon", "neta", "нета", "хозон", "нэта"]),
    ("IM Motors", ["im motors", "im", "zhiji", "zhizi", "жижи", "им моторс", "им"]),
    ("Jidu", ["jidu", "жиду", "джиду"]),
    ("Forthing", ["forthing", "форфинг", "форфин"]),
    ("Livan", ["livan", "ливан"]),
    ("Liebao", ["liebao", "leopaard", "leopard", "леопард", "либао", "fangchengbao", "фанченбао"]),
    ("Rising Auto", ["rising auto", "rising", "feifan", "фейфан", "райзинг"]),
    ("Maextro", ["maextro", "маэкстро", "маекстро"]),
    ("Yipai", ["yipai", "eπ", "epi", "ипай", "иpai", "епай"]),
    ("Radar", ["radar", "радар"]),
    ("Enovate", ["enovate", "enoreve", "энорев", "эновейт"]),
    ("Jetta", ["jetta", "джетта"]),
    ("Polar Stone", ["polar stone", "jishi", "jishi auto", "полар стоун", "джиши", "цзиши"]),
    # --- Россия / СНГ ---
    ("Lada", ["lada", "лада", "ваз", "vaz"]),
    ("UAZ", ["uaz", "уаз"]),
    ("GAZ", ["gaz", "газ"]),
    ("Moskvich", ["moskvich", "москвич", "москвичь"]),
    ("Aurus", ["aurus", "аурус"]),
    ("Evolute", ["evolute", "эволют", "эволюте"]),
    ("Belgee", ["belgee", "белджи"]),
    ("Ravon", ["ravon", "равон"]),
    # --- Корея (исторические) ---
    ("Daewoo", ["daewoo", "дэу", "деу", "дэуо"]),
    ("SsangYong", ["ssangyong", "ssang yong", "санг йонг", "сангенг", "ссанг йонг"]),
    # --- Другие ---
    ("Tata", ["tata", "тата"]),
    ("Mahindra", ["mahindra", "махиндра"]),
    ("Proton", ["proton", "протон"]),
    ("Perodua", ["perodua", "перодуа"]),
    ("Holden", ["holden", "холден"]),
    ("Iveco", ["iveco", "ивеко"]),
    ("Mitsuoka", ["mitsuoka", "митсуока"]),
]

# canonical -> [aliases]
MODEL_ALIAS_GROUPS: list[tuple[str, list[str]]] = [
    # --- Toyota ---
    ("Camry", ["камри", "camry"]),
    ("Corolla", ["королла", "corolla"]),
    ("Land Cruiser", ["ленд крузер", "land cruiser", "landcruiser", "лэнд крузер"]),
    ("RAV4", ["рав 4", "rav4", "rav 4", "рав4", "равчик"]),
    ("Prado", ["прадо", "prado"]),
    ("Hilux", ["хайлюкс", "hilux"]),
    ("Highlander", ["хайлендер", "хайлендэр", "highlander"]),
    ("Fortuner", ["фортунер", "fortuner"]),
    ("Sequoia", ["секвойя", "sequoia"]),
    ("Tundra", ["тундра", "tundra"]),
    ("Venza", ["венза", "venza"]),
    ("Yaris", ["ярис", "yaris"]),
    ("Supra", ["супра", "supra"]),
    ("C-HR", ["c-hr", "c hr", "chr", "с-хр"]),
    ("bZ4X", ["bz4x", "bZ4X", "бз4х"]),
    ("Alphard", ["альфард", "alphard"]),
    ("Avensis", ["авенсис", "avensis"]),
    ("Auris", ["аурис", "auris"]),
    ("Crown", ["краун", "crown"]),
    ("Sienna", ["сиенна", "sienna"]),
    ("4Runner", ["4runner", "4 runner", "фораннер", "4 раннер"]),
    ("Tacoma", ["такома", "tacoma"]),
    # --- BMW ---
    ("X1", ["х1", "x1"]),
    ("X2", ["х2", "x2"]),
    ("X3", ["х3", "x3"]),
    ("X4", ["х4", "x4"]),
    ("X5", ["х5", "x5"]),
    ("X6", ["х6", "x6"]),
    ("X7", ["х7", "x7"]),
    ("XM", ["xm", "хм"]),
    ("1 Series", ["1 серии", "1 series", "1-series", "1 серия"]),
    ("2 Series", ["2 серии", "2 series", "2-series", "2 серия"]),
    ("3 Series", ["3 серии", "3 series", "3-series", "3 серия"]),
    ("4 Series", ["4 серии", "4 series", "4-series", "4 серия"]),
    ("5 Series", ["5 серии", "5 series", "5-series", "5 серия"]),
    ("6 Series", ["6 серии", "6 series", "6-series"]),
    ("7 Series", ["7 серии", "7 series", "7-series", "7 серия"]),
    ("8 Series", ["8 серии", "8 series", "8-series"]),
    ("M3", ["m3", "м3"]),
    ("M4", ["m4", "м4"]),
    ("M5", ["m5", "м5"]),
    ("M8", ["m8", "м8"]),
    ("i3", ["i3", "и3"]),
    ("i4", ["i4", "и4"]),
    ("i5", ["i5", "и5"]),
    ("i7", ["i7", "и7"]),
    ("iX", ["ix", "i x", "икс"]),
    ("iX1", ["ix1", "i x1"]),
    ("iX3", ["ix3", "i x3"]),
    ("Z4", ["z4", "з4"]),
    ("M2", ["m2", "м2"]),
    ("iX2", ["ix2", "i x2"]),
    ("2 Series Active Tourer", ["2 series active tourer", "2 серии active tourer"]),
    ("A-Class", ["а класс", "a class", "a-class", "a-класс", "а-класс"]),
    ("B-Class", ["б класс", "b class", "b-class", "b-класс"]),
    ("C-Class", ["с класс", "c class", "c-class", "c-класс", "с-класс"]),
    ("E-Class", ["е класс", "e class", "e-class", "e-класс", "е-класс"]),
    ("S-Class", ["s класс", "s class", "s-class", "s-класс", "с-класс"]),
    ("CLA", ["cla", "кла"]),
    ("CLS", ["cls", "клс"]),
    ("GLA", ["gla", "гла"]),
    ("GLB", ["glb", "гльб"]),
    ("GLC", ["glc", "глк", "glc"]),
    ("GLE", ["gle", "гле"]),
    ("GLS", ["gls", "глс"]),
    ("G-Class", ["g class", "g-class", "g класс", "гелик", "гелендваген", "geländewagen"]),
    ("AMG GT", ["amg gt", "amg-gt", "амг гт"]),
    ("V-Class", ["v class", "v-class", "v класс"]),
    ("Sprinter", ["спринтер", "sprinter"]),
    ("Vito", ["вито", "vito"]),
    ("Maybach S-Class", ["maybach s class", "maybach s-class", "майбах s"]),
    ("EQA", ["eqa", "екуа", "экьюа"]),
    ("EQB", ["eqb", "екуб", "экьюб"]),
    ("EQC", ["eqc", "еквс", "экьюси"]),
    ("EQE", ["eqe", "екуе", "экьюе"]),
    ("EQS", ["eqs", "екус", "экьюес"]),
    ("CLE", ["cle", "кле"]),
    ("SL", ["sl", "сл"]),
    ("SLC", ["slc", "слс"]),
    # --- Audi ---
    ("A1", ["a1", "а1"]),
    ("A3", ["a3", "а3"]),
    ("A4", ["a4", "а4"]),
    ("A5", ["a5", "а5"]),
    ("A6", ["a6", "а6"]),
    ("A7", ["a7", "а7"]),
    ("A8", ["a8", "а8"]),
    ("Q2", ["q2", "к2"]),
    ("Q3", ["q3", "к3"]),
    ("Q4", ["q4", "к4"]),
    ("Q5", ["q5", "к5"]),
    ("Q7", ["q7", "к7"]),
    ("Q8", ["q8", "к8"]),
    ("e-tron", ["e-tron", "e tron", "етрон", "и-трон"]),
    ("TT", ["tt", "тт"]),
    ("R8", ["r8", "р8"]),
    ("RS6", ["rs6", "рс6"]),
    ("RS7", ["rs7", "рс7"]),
    ("SQ5", ["sq5", "ску5"]),
    ("SQ7", ["sq7", "ску7"]),
    ("RS Q8", ["rs q8", "рс q8"]),
    ("Q6 e-tron", ["q6 e-tron", "q6 etron", "к6 етрон"]),
    ("S3", ["s3", "с3"]),
    ("S4", ["s4", "с4"]),
    # --- Volkswagen ---
    ("Golf", ["гольф", "golf"]),
    ("Passat", ["пассат", "passat"]),
    ("Polo", ["поло", "polo"]),
    ("Jetta", ["джетта", "jetta"]),
    ("Tiguan", ["тигуан", "tiguan"]),
    ("Touareg", ["туарег", "touareg"]),
    ("Teramont", ["терамонт", "teramont", "атлас"]),  # Teramont = Atlas in some markets
    ("Arteon", ["артеон", "arteon"]),
    ("Amarok", ["амарок", "amarok"]),
    ("ID.3", ["id3", "id 3", "id.3"]),
    ("ID.4", ["id4", "id 4", "id.4"]),
    ("ID.6", ["id6", "id 6", "id.6"]),
    ("Taos", ["таос", "taos"]),
    ("T-Cross", ["t-cross", "t cross", "т-кросс"]),
    ("T-Roc", ["t-roc", "t roc", "т-рок"]),
    ("Multivan", ["multivan", "мультивэн"]),
    ("Caravelle", ["caravelle", "каравелла"]),
    ("Crafter", ["crafter", "крафтер"]),
    ("ID.7", ["id7", "id 7", "id.7"]),
    ("ID.Buzz", ["id buzz", "id.buzz", "ид бас"]),
    ("Caddy", ["caddy", "кэдди", "кедди"]),
    ("Touran", ["touran", "туран"]),
    # --- Lexus ---
    ("RX", ["rx", "рх"]),
    ("NX", ["nx", "нх"]),
    ("LX", ["lx", "лх"]),
    ("GX", ["gx", "гх"]),
    ("ES", ["es", "ес"]),
    ("LS", ["ls", "лс"]),
    ("IS", ["is", "ис"]),
    ("UX", ["ux", "юх"]),
    ("RC", ["rc", "рц"]),
    ("LC", ["lc", "лц"]),
    # --- Honda ---
    ("Accord", ["аккорд", "accord"]),
    ("Civic", ["сивик", "civic"]),
    ("CR-V", ["cr-v", "crv", "cr v", "црв"]),
    ("HR-V", ["hr-v", "hrv", "hr v"]),
    ("Pilot", ["пилот", "pilot"]),
    ("Odyssey", ["одиссей", "odyssey"]),
    ("Fit", ["фит", "fit"]),
    ("Jazz", ["джаз", "jazz"]),
    ("City", ["сити", "city"]),
    ("Ridgeline", ["риджлайн", "ridgeline"]),
    # --- Nissan ---
    ("Qashqai", ["кашкай", "qashqai"]),
    ("X-Trail", ["x-trail", "x trail", "xтрейл", "x-трейл", "икстрейл", "икс трейл"]),
    ("Pathfinder", ["патфайндер", "pathfinder"]),
    ("Murano", ["мурано", "murano"]),
    ("Almera", ["альмера", "almera"]),
    ("Juke", ["джук", "juke"]),
    ("Leaf", ["лиф", "leaf"]),
    ("Patrol", ["патруль", "patrol"]),
    ("Navara", ["навара", "navara"]),
    ("Sentra", ["сентра", "sentra"]),
    ("Maxima", ["максима", "maxima"]),
    ("GT-R", ["gt-r", "gtr", "gt r", "гтр"]),
    ("Tiida", ["тиида", "tiida"]),
    ("Teana", ["теана", "teana"]),
    ("Terrano", ["террано", "terrano"]),
    # --- Hyundai ---
    ("Solaris", ["солярис", "solaris"]),
    ("Creta", ["крета", "creta"]),
    ("Tucson", ["туксон", "tucson"]),
    ("Sonata", ["соната", "sonata"]),
    ("Elantra", ["элантра", "elantra"]),
    ("Santa Fe", ["santa fe", "санта фе", "сантафе"]),
    ("Palisade", ["палисад", "palisade"]),
    ("Kona", ["кона", "kona"]),
    ("Venue", ["веню", "venue"]),
    ("i30", ["i30", "и30"]),
    ("i40", ["i40", "и40"]),
    ("Staria", ["стария", "staria"]),
    ("Ioniq", ["ioniq", "ионик", "ионик"]),
    ("Ioniq 5", ["ioniq 5", "ионик 5"]),
    ("Ioniq 6", ["ioniq 6", "ионик 6"]),
    # --- Kia ---
    ("Rio", ["рио", "rio"]),
    ("Ceed", ["сид", "ceed", "ced", "сид"]),
    ("Sportage", ["спортейдж", "sportage"]),
    ("Soul", ["соул", "soul"]),
    ("Cerato", ["церато", "cerato"]),
    ("Sorento", ["соренто", "sorento"]),
    ("Carnival", ["карнивал", "carnival"]),
    ("Stinger", ["стингер", "stinger"]),
    ("K5", ["k5", "к5"]),
    ("K8", ["k8", "к8"]),
    ("Seltos", ["селтос", "seltos"]),
    ("Mohave", ["мохаве", "mohave", "борего"]),
    ("EV6", ["ev6", "ev 6"]),
    ("EV9", ["ev9", "ev 9"]),
    # --- Mazda ---
    ("Mazda3", ["mazda3", "mazda 3", "мазда3", "мазда 3"]),
    ("Mazda6", ["mazda6", "mazda 6", "мазда6", "мазда 6"]),
    ("CX-3", ["cx-3", "cx 3"]),
    ("CX-5", ["cx-5", "cx 5", "сх5", "цх5"]),
    ("CX-9", ["cx-9", "cx 9"]),
    ("CX-30", ["cx-30", "cx 30"]),
    ("CX-60", ["cx-60", "cx 60"]),
    ("MX-5", ["mx-5", "mx 5", "миата", "miata"]),
    # --- Subaru ---
    ("Forester", ["форестер", "forester"]),
    ("Outback", ["аутбек", "outback"]),
    ("Impreza", ["импреза", "impreza"]),
    ("WRX", ["wrx", "врх"]),
    ("XV", ["xv", "ксв"]),
    ("Legacy", ["легаси", "legacy"]),
    ("Ascent", ["асент", "ascent"]),
    ("BRZ", ["brz", "брз"]),
    # --- Volvo ---
    ("XC40", ["xc40", "xc 40", "хс40"]),
    ("XC60", ["xc60", "xc 60", "хс60"]),
    ("XC90", ["xc90", "xc 90", "хс90"]),
    ("S60", ["s60", "s 60"]),
    ("S90", ["s90", "s 90"]),
    ("V60", ["v60", "v 60"]),
    ("V90", ["v90", "v 90"]),
    ("C40", ["c40", "c 40"]),
    ("EX30", ["ex30", "ex 30"]),
    ("EX90", ["ex90", "ex 90"]),
    ("XC70", ["xc70", "xc 70"]),
    ("EM90", ["em90", "em 90"]),
    # --- Ford ---
    ("Focus", ["фокус", "focus"]),
    ("Fiesta", ["фиеста", "fiesta"]),
    ("Mondeo", ["мондео", "mondeo"]),
    ("Fusion", ["фьюжн", "fusion"]),
    ("Mustang", ["мустанг", "mustang"]),
    ("Explorer", ["эксплорер", "explorer"]),
    ("Escape", ["эскейп", "escape", "кьюга", "kuga"]),
    ("Kuga", ["kuga", "куга"]),
    ("Bronco", ["бронко", "bronco"]),
    ("F-150", ["f-150", "f 150", "f150", "эф 150"]),
    ("Ranger", ["рейнджер", "ranger"]),
    ("Edge", ["эдж", "edge"]),
    ("Expedition", ["экспедишн", "expedition"]),
    ("Transit", ["транзит", "transit"]),
    ("Puma", ["пума", "puma"]),
    # --- Chevrolet ---
    ("Cruze", ["круз", "cruze"]),
    ("Malibu", ["малибу", "malibu"]),
    ("Tahoe", ["тахо", "tahoe"]),
    ("Suburban", ["сабурбан", "suburban"]),
    ("Camaro", ["камаро", "camaro"]),
    ("Corvette", ["корвет", "corvette"]),
    ("Equinox", ["эквинокс", "equinox"]),
    ("Traverse", ["траверс", "traverse"]),
    ("Captiva", ["каптива", "captiva"]),
    ("Aveo", ["авео", "aveo"]),
    ("Lacetti", ["лачетти", "lacetti"]),
    ("Niva", ["нива", "niva"]),
    ("Silverado", ["сильверадо", "silverado"]),
    ("Colorado", ["колорадо", "colorado"]),
    ("Blazer", ["блейзер", "blazer"]),
    # --- Jeep ---
    ("Wrangler", ["вранглер", "wrangler"]),
    ("Cherokee", ["чероки", "cherokee"]),
    ("Grand Cherokee", ["grand cherokee", "гранд чероки"]),
    ("Compass", ["компас", "compass"]),
    ("Renegade", ["ренегат", "renegade"]),
    ("Gladiator", ["гладиатор", "gladiator"]),
    ("Wagoneer", ["вагонир", "wagoneer"]),
    # --- Tesla ---
    ("Model 3", ["model 3", "модель 3"]),
    ("Model Y", ["model y", "модель y"]),
    ("Model S", ["model s", "модель s"]),
    ("Model X", ["model x", "модель x"]),
    ("Cybertruck", ["cybertruck", "кибертрак", "сайбертрак"]),
    # --- GMC ---
    ("Sierra", ["sierra", "сьерра", "сиерра"]),
    ("Sierra 1500", ["sierra 1500", "gmc sierra 1500", "сьерра 1500"]),
    ("Sierra 2500", ["sierra 2500", "gmc sierra 2500"]),
    ("Sierra 3500", ["sierra 3500", "gmc sierra 3500"]),
    ("Yukon", ["yukon", "юкон"]),
    ("Yukon XL", ["yukon xl", "юкон xl"]),
    ("Acadia", ["acadia", "акадия"]),
    ("Terrain", ["terrain", "террейн", "терен"]),
    ("Canyon", ["canyon", "каньон"]),
    ("Hummer EV", ["hummer ev", "хаммер ev"]),
    # --- Dodge ---
    ("Charger", ["charger", "чарджер"]),
    ("Challenger", ["challenger", "челленджер"]),
    ("Durango", ["durango", "дуранго"]),
    ("Journey", ["journey", "джорни", "джёрни"]),
    ("Dart", ["dart", "дарт"]),
    ("Nitro", ["nitro", "нитро"]),
    ("Hornet", ["hornet", "хорнет"]),
    ("Caravan", ["caravan", "караван"]),
    ("Caliber", ["caliber", "калибер"]),
    # --- Chrysler ---
    ("Pacifica", ["pacifica", "пацифика"]),
    ("300", ["chrysler 300", "крайслер 300"]),
    ("200", ["chrysler 200", "крайслер 200"]),
    ("Town & Country", ["town country", "town & country", "таун энд кантри"]),
    ("Voyager", ["chrysler voyager", "вояджер"]),
    # --- Buick ---
    ("Enclave", ["enclave", "энклав"]),
    ("Encore", ["encore", "анкор", "энкор"]),
    ("Envision", ["envision", "энвижн", "энвизион"]),
    ("LaCrosse", ["lacrosse", "лакросс", "лакрос"]),
    ("Regal", ["regal", "ригал", "регал"]),
    ("Verano", ["verano", "верано"]),
    ("GL8", ["gl8", "гл8"]),
    # --- Ram ---
    ("Ram 1500", ["ram 1500", "рам 1500"]),
    ("Ram 2500", ["ram 2500", "рам 2500"]),
    ("Ram 3500", ["ram 3500", "рам 3500"]),
    ("ProMaster", ["promaster", "pro master", "промастер"]),
    ("Rampage", ["rampage", "рампейдж"]),
    # --- Rivian ---
    ("R1T", ["r1t", "r1 t", "р1т"]),
    ("R1S", ["r1s", "r1 s", "р1с"]),
    ("R2", ["r2", "rivian r2", "р2"]),
    # --- Lucid ---
    ("Air", ["lucid air", "люсид эйр", "эйр"]),
    ("Gravity", ["lucid gravity", "гравити", "гравити"]),
    # --- Porsche ---
    ("Cayenne", ["кайен", "cayenne"]),
    ("Macan", ["макан", "macan"]),
    ("Panamera", ["панамера", "panamera"]),
    ("Taycan", ["тайкан", "taycan"]),
    ("911", ["911", "nine eleven"]),
    ("Boxster", ["бокстер", "boxster"]),
    ("Cayman", ["кайман", "cayman"]),
    ("718", ["718", "семьсот восемнадцать"]),
    ("918 Spyder", ["918 spyder", "918", "918 спайдер"]),
    # --- Land Rover / Range Rover ---
    ("Defender", ["дефендер", "defender"]),
    ("Discovery", ["дискавери", "discovery"]),
    ("Discovery Sport", ["discovery sport", "дискавери спорт"]),
    ("Range Rover Sport", ["range rover sport", "рендж ровер спорт"]),
    ("Range Rover Evoque", ["range rover evoque", "evoque", "эвок", "эвок"]),
    ("Freelander", ["фрилендер", "freelander"]),
    ("Velar", ["велар", "velar"]),
    ("Range Rover", ["range rover", "рендж ровер"]),
    ("Range Rover Velar", ["range rover velar", "рендж ровер велар"]),
    # --- Renault ---
    ("Duster", ["дастер", "duster"]),
    ("Logan", ["логан", "logan"]),
    ("Sandero", ["сандеро", "sandero"]),
    ("Arkana", ["аркана", "arkana"]),
    ("Kaptur", ["каптюр", "kaptur"]),
    ("Megane", ["меган", "megane"]),
    ("Fluence", ["флюенс", "fluence"]),
    ("Koleos", ["колеос", "koleos"]),
    ("Scenic", ["сценик", "scenic"]),
    ("Clio", ["клио", "clio"]),
    ("Talisman", ["талиcман", "talisman"]),
    ("Espace", ["эспас", "espace"]),
    ("Kangoo", ["кангу", "kangoo"]),
    ("Zoe", ["zoe", "зоэ"]),
    ("Austral", ["австрал", "austral"]),
    ("Master", ["мастер", "master"]),
    # --- Peugeot ---
    ("3008", ["3008"]),
    ("5008", ["5008"]),
    ("408", ["408"]),
    ("308", ["308"]),
    ("2008", ["2008"]),
    ("Partner", ["партнер", "partner"]),
    ("508", ["508"]),
    ("207", ["207"]),
    ("406", ["406"]),
    ("107", ["107"]),
    ("Rifter", ["рифтер", "rifter"]),
    ("Traveller", ["тревеллер", "traveller"]),
  # --- Skoda ---
    ("Octavia", ["октавия", "octavia"]),
    ("Rapid", ["рапид", "rapid"]),
    ("Superb", ["суперб", "superb"]),
    ("Kodiaq", ["кодиак", "kodiaq"]),
    ("Karoq", ["карок", "karoq"]),
    ("Kamiq", ["камик", "kamiq"]),
    ("Fabia", ["фабия", "fabia"]),
    ("Scala", ["скала", "scala"]),
    ("Enyaq", ["enyaq", "еняк", "эньяк"]),
    ("Yeti", ["йети", "yeti"]),
    ("Roomster", ["румстер", "roomster"]),
    # --- Mitsubishi ---
    ("Outlander", ["аутлендер", "outlander"]),
    ("Pajero", ["паджеро", "pajero"]),
    ("Pajero Sport", ["pajero sport", "паджеро спорт"]),
    ("Lancer", ["лансер", "lancer"]),
    ("ASX", ["asx", "асх"]),
    ("Eclipse Cross", ["eclipse cross", "эклипс кросс"]),
    ("L200", ["l200", "l 200"]),
    # --- Suzuki ---
    ("Vitara", ["витара", "vitara"]),
    ("Grand Vitara", ["grand vitara", "гранд витара"]),
    ("Jimny", ["джимни", "jimny"]),
    ("Swift", ["свифт", "swift"]),
    ("SX4", ["sx4", "sx 4"]),
    # --- Chinese: BYD ---
    ("Song", ["song", "сонг"]),
    ("Song Plus", ["song plus", "сонг плюс"]),
    ("Han", ["han", "хан"]),
    ("Tang", ["tang", "тан"]),
    ("Seal", ["seal", "сил"]),
    ("Dolphin", ["dolphin", "дельфин"]),
    ("Atto 3", ["atto 3", "atto3", "атто 3"]),
    ("Yuan Plus", ["yuan plus", "юань плюс"]),
    ("Seagull", ["seagull", "чайка"]),
    # --- Chinese: Haval ---
    ("Jolion", ["джолион", "jolion"]),
    ("F7", ["f7", "ф7"]),
    ("H6", ["h6", "х6"]),
    ("H9", ["h9", "х9"]),
    ("Dargo", ["дарго", "dargo"]),
    ("M6", ["m6", "м6"]),
    # --- Chinese: Chery / Exeed ---
    ("Tiggo", ["тигго", "tiggo"]),
    ("Tiggo 4", ["tiggo 4", "тигго 4"]),
    ("Tiggo 7", ["tiggo 7", "тигго 7"]),
    ("Tiggo 8", ["tiggo 8", "тигго 8"]),
    ("Arrizo", ["арризо", "arrizo"]),
    ("Omoda 5", ["omoda 5", "омода 5"]),
    ("TXL", ["txl", "тхл"]),
    ("VX", ["vx", "вх"]),
    # --- Chinese: Geely ---
    ("Monjaro", ["монжаро", "monjaro"]),
    ("Coolray", ["кулрей", "coolray"]),
    ("Atlas", ["атлас", "atlas"]),
    ("Atlas Pro", ["atlas pro", "атлас про"]),
    ("Tugella", ["тугелла", "tugella"]),
    ("Emgrand", ["эмгранд", "emgrand"]),
    ("Preface", ["префейс", "preface"]),
    # --- Chinese: Changan ---
    ("CS35", ["cs35", "cs 35"]),
    ("CS55", ["cs55", "cs 55"]),
    ("CS75", ["cs75", "cs 75"]),
    ("CS85", ["cs85", "cs 85"]),
    ("UNI-K", ["uni-k", "uni k", "уни к"]),
    ("UNI-T", ["uni-t", "uni t", "уни т"]),
    # --- Chinese: Li Auto / NIO / Xpeng / Zeekr ---
    ("L7", ["l7", "л7"]),
    ("L8", ["l8", "л8"]),
    ("L9", ["l9", "л9"]),
    ("ET5", ["et5", "ет5"]),
    ("ET7", ["et7", "ет7"]),
    ("ES6", ["es6", "ес6"]),
    ("ES8", ["es8", "ес8"]),
    ("P7", ["p7", "п7"]),
    ("G6", ["g6", "г6"]),
    ("G9", ["g9", "г9"]),
    ("001", ["001", "зикр 001"]),
    # --- Chinese: Aion ---
    ("Aion V", ["aion v", "айон v", "айон в", "аион v"]),
    ("Aion Y", ["aion y", "айон y", "аион y"]),
    ("Aion S", ["aion s", "айон s", "аион s"]),
    ("Aion LX", ["aion lx", "айон lx"]),
    ("Aion UT", ["aion ut", "айон ut"]),
    ("Hyper GT", ["hyper gt", "aion hyper gt", "хайпер гт"]),
    # --- Chinese: Xiaomi ---
    ("SU7", ["su7", "su 7", "су7"]),
    ("SU7 Ultra", ["su7 ultra", "су7 ультра"]),
    ("YU7", ["yu7", "yu 7", "ю7"]),
    # --- Chinese: Denza ---
    ("D9", ["d9", "д9", "denza d9", "дэнза d9"]),
    ("N7", ["n7", "н7", "denza n7"]),
    ("N8", ["n8", "н8", "denza n8"]),
    ("N9", ["n9", "н9", "denza n9"]),
    ("Z9", ["z9", "з9", "denza z9"]),
    # --- Chinese: HiPhi ---
    ("HiPhi X", ["hiphi x", "хифи x", "хаифи x"]),
    ("HiPhi Y", ["hiphi y", "хифи y"]),
    ("HiPhi Z", ["hiphi z", "хифи z"]),
    # --- Chinese: GAC Trumpchi ---
    ("GS8", ["gs8", "gs 8", "гс8"]),
    ("GS4", ["gs4", "gs 4", "гс4"]),
    ("GS3", ["gs3", "gs 3", "гс3"]),
    ("M8", ["m8", "м8", "trumpchi m8"]),
    ("Empow", ["empow", "эмпау", "эмпао"]),
    # --- Chinese: Baojun ---
    ("Yep", ["yep", "еп", "йеп"]),
    ("Yunduo", ["yunduo", "юндо", "юньдо"]),
    ("KiWi EV", ["kiwi ev", "kiwi", "киви"]),
    ("E300", ["e300", "e 300", "е300"]),
    # --- Chinese: iCar ---
    ("iCar 03", ["icar 03", "icar03", "айкар 03", "икар 03"]),
    ("V23", ["v23", "в23", "icar v23"]),
    # --- Chinese: Hozon (Neta) ---
    ("Neta S", ["neta s", "нета s", "hozon s"]),
    ("Neta GT", ["neta gt", "нета гт"]),
    ("Neta L", ["neta l", "нета l"]),
    ("Neta U", ["neta u", "нета u"]),
    ("Neta Aya", ["neta aya", "нета ая"]),
    # --- Chinese: IM Motors ---
    ("IM L6", ["im l6", "zhiji l6", "жижи l6", "им l6"]),
    ("IM L7", ["im l7", "zhiji l7", "жижи l7", "им l7"]),
    ("IM LS7", ["im ls7", "zhiji ls7", "им ls7"]),
    # --- Chinese: Jidu ---
    ("Robo-01", ["robo-01", "robo 01", "робо 01"]),
    ("Robo-07", ["robo-07", "robo 07", "робо 07"]),
    # --- Chinese: Forthing ---
    ("T5 EVO", ["t5 evo", "т5 ево"]),
    ("Yacht", ["yacht", "яхта", "йатч"]),
    ("Thunder", ["thunder", "тандер"]),
    ("U-Tour", ["u-tour", "u tour", "ю тур"]),
    # --- Chinese: Livan ---
    ("X3 Pro", ["x3 pro", "x3 про", "ливан x3 pro"]),
    ("X6 Pro", ["x6 pro", "x6 про"]),
    ("RL9", ["rl9", "рл9"]),
    ("S6", ["livan s6", "ливан s6"]),
    # --- Chinese: Liebao ---
    ("Bao 5", ["bao 5", "bao5", "бao 5", "леопард 5", "fangchengbao 5"]),
    ("Bao 8", ["bao 8", "bao8", "бao 8", "леопард 8", "fangchengbao 8"]),
    # --- Chinese: Rising Auto ---
    ("R7", ["r7", "р7", "rising r7", "feifan r7"]),
    ("Rising F7", ["rising f7", "feifan f7", "фейфан f7"]),
    ("ER6", ["er6", "ер6", "rising er6"]),
    # --- Chinese: Maextro ---
    ("Maextro S800", ["maextro s800", "s800", "маэкстро s800"]),
    # --- Chinese: Yipai ---
    ("eπ 007", ["eπ 007", "epi 007", "yipai 007", "ипай 007"]),
    ("eπ 008", ["eπ 008", "epi 008", "yipai 008", "ипай 008"]),
    # --- Chinese: Radar ---
    ("RD6", ["rd6", "rd 6", "рд6"]),
    ("RD5", ["rd5", "rd 5", "рд5"]),
    # --- Chinese: Enovate ---
    ("ME5", ["me5", "me 5", "мe5", "enovate me5"]),
    ("ME7", ["me7", "me 7", "enovate me7"]),
    # --- Chinese: Jetta (FAW-VW) ---
    ("VS5", ["vs5", "vs 5", "вс5"]),
    ("VS7", ["vs7", "vs 7", "вс7"]),
    ("VA3", ["va3", "va 3", "ва3"]),
    ("VS6", ["vs6", "vs 6"]),
    # --- Chinese: Polar Stone ---
    ("Polar Stone 01", ["polar stone 01", "jishi 01", "джиши 01"]),
    ("Polar Stone L7", ["polar stone l7", "jishi l7", "джиши l7"]),
    # --- Jaguar ---
    ("F-Pace", ["f-pace", "f pace", "ф-пейс", "ф пейс"]),
    ("E-Pace", ["e-pace", "e pace", "е-пейс"]),
    ("I-Pace", ["i-pace", "i pace", "ай-пейс"]),
    ("XE", ["xe", "ксе"]),
    ("XF", ["xf", "ксф"]),
    ("XJ", ["xj", "ксж"]),
    ("F-Type", ["f-type", "f type", "ф-тап", "ф тайп"]),
    # --- Mini ---
    ("Cooper", ["cooper", "купер"]),
    ("Countryman", ["countryman", "кантримен", "кантриман"]),
    ("Clubman", ["clubman", "клабмен"]),
    ("Paceman", ["paceman", "пейсмен"]),
    ("Aceman", ["aceman", "эйсмен"]),
    # --- Bentley ---
    ("Continental GT", ["continental gt", "континенталь gt"]),
    ("Flying Spur", ["flying spur", "флаинг спур"]),
    ("Bentayga", ["bentayga", "бентайга"]),
    ("Mulsanne", ["mulsanne", "мюлсанн"]),
    # --- Rolls-Royce ---
    ("Ghost", ["ghost", "гост", "гоуст"]),
    ("Phantom", ["phantom", "фантом"]),
    ("Wraith", ["wraith", "рейф", "рейс"]),
    ("Dawn", ["dawn", "дон"]),
    ("Cullinan", ["cullinan", "куллинан"]),
    ("Spectre", ["spectre", "спектр"]),
    # --- Aston Martin ---
    ("DB11", ["db11", "дб11"]),
    ("DB12", ["db12", "дб12"]),
    ("Vantage", ["vantage", "вантедж"]),
    ("DBS", ["dbs", "дбс"]),
    ("DBX", ["dbx", "дбх"]),
    # --- McLaren ---
    ("720S", ["720s", "720 s"]),
    ("570S", ["570s", "570 s"]),
    ("765LT", ["765lt", "765 lt"]),
    ("Artura", ["artura", "артура"]),
    ("GT", ["mclaren gt", "макларен gt"]),
    # --- Ferrari ---
    ("Roma", ["roma", "рома"]),
    ("Portofino", ["portofino", "портофино"]),
    ("SF90", ["sf90", "сф90"]),
    ("296", ["296", "296 gtb"]),
    ("F8", ["f8", "f8 tributo", "ф8"]),
    ("Purosangue", ["purosangue", "пуросангуэ"]),
    ("812", ["812", "812 superfast"]),
    # --- Lamborghini ---
    ("Urus", ["urus", "урус"]),
    ("Huracan", ["huracan", "уракан", "хуракан"]),
    ("Aventador", ["aventador", "авентадор"]),
    ("Revuelto", ["revuelto", "ревуэльто"]),
    # --- Maserati ---
    ("Ghibli", ["ghibli", "гибли"]),
    ("Quattroporte", ["quattroporte", "кватропорте"]),
    ("Levante", ["levante", "леванте"]),
    ("Grecale", ["grecale", "грекале"]),
    ("MC20", ["mc20", "мс20"]),
    ("GranTurismo", ["granturismo", "грантуризмо"]),
    # --- Alfa Romeo ---
    ("Giulia", ["giulia", "джулия", "гиулия"]),
    ("Stelvio", ["stelvio", "стелвио"]),
    ("Tonale", ["tonale", "тонале"]),
    ("Giulietta", ["giulietta", "джульетта"]),
    ("4C", ["4c", "4 c"]),
    ("MiTo", ["mito", "мито"]),
    # --- Lancia ---
    ("Ypsilon", ["ypsilon", "ипсилон"]),
    ("Delta", ["delta", "дельта"]),
    ("Thesis", ["thesis", "тезис"]),
    # --- Abarth ---
    ("Abarth 500", ["abarth 500", "абарт 500"]),
    ("Abarth 595", ["abarth 595", "абарт 595"]),
    ("Abarth 695", ["abarth 695", "абарт 695"]),
    ("Abarth 124 Spider", ["abarth 124 spider", "абарт 124"]),
    # --- DS ---
    ("DS 3", ["ds 3", "дс 3"]),
    ("DS 4", ["ds 4", "дс 4"]),
    ("DS 7", ["ds 7", "дс 7"]),
    ("DS 9", ["ds 9", "дс 9"]),
    # --- Alpine ---
    ("A110", ["a110", "a 110", "а110"]),
    # --- Polestar ---
    ("Polestar 2", ["polestar 2", "полестар 2"]),
    ("Polestar 3", ["polestar 3", "полестар 3"]),
    ("Polestar 4", ["polestar 4", "полестар 4"]),
    # --- Saab ---
    ("9-3", ["9-3", "9 3", "93"]),
    ("9-5", ["9-5", "9 5", "95"]),
    ("900", ["900", "сааб 900"]),
    # --- Seat ---
    ("Ibiza", ["ibiza", "ибиза"]),
    ("Leon", ["leon", "леон"]),
    ("Arona", ["arona", "арона"]),
    ("Tarraco", ["tarraco", "таррако"]),
    ("Alhambra", ["alhambra", "альгамбра"]),
  # --- Rimac ---
    ("Nevera", ["nevera", "невера"]),
    ("Concept One", ["concept one", "концепт уан"]),
    # --- Smart ---
    ("Fortwo", ["fortwo", "for two", "форту"]),
    ("Forfour", ["forfour", "for four", "форфор"]),
    ("Smart #1", ["smart 1", "smart #1", "смарт 1"]),
    ("Smart #3", ["smart 3", "smart #3", "смарт 3"]),
    # --- Lada / российские ---
    ("Vesta", ["веста", "vesta"]),
    ("Granta", ["гранта", "granta"]),
    ("Largus", ["ларгус", "largus"]),
    ("XRAY", ["xray", "x-ray", "x ray", "иксрей"]),
    ("Niva Travel", ["niva travel", "нива тревел"]),
    ("Patriot", ["патриот", "patriot"]),
    ("Hunter", ["хантер", "hunter"]),
    ("Pickup", ["пикап", "pickup"]),
    ("Соболь", ["соболь", "sobol"]),
    ("Газель", ["газель", "gazelle"]),
    # --- Dacia ---
    ("Spring", ["spring", "спринг"]),
    ("Jogger", ["jogger", "джоггер"]),
    ("Lodgy", ["lodgy", "лоджи"]),
    ("Dokker", ["dokker", "доккер"]),
    ("Bigster", ["bigster", "бигстер"]),
    # --- Opel ---
    ("Astra", ["астра", "astra"]),
    ("Insignia", ["инсигния", "insignia"]),
    ("Mokka", ["мокка", "mokka"]),
    ("Crossland", ["кроссланд", "crossland"]),
    ("Grandland", ["грандланд", "grandland"]),
    ("Corsa", ["корса", "corsa"]),
    ("Zafira", ["зафира", "zafira"]),
    ("Vivaro", ["виваро", "vivaro"]),
    ("Combo", ["комбо", "combo"]),
    ("Meriva", ["мерива", "meriva"]),
    # --- Fiat ---
    ("500", ["500", "пятисотый"]),
    ("Panda", ["панда", "panda"]),
    ("Tipo", ["типо", "tipo"]),
    ("Doblo", ["добло", "doblo"]),
    ("Punto", ["пунто", "punto"]),
    ("Bravo", ["браво", "bravo"]),
    ("Linea", ["линеа", "linea"]),
    ("Freemont", ["фримонт", "freemont"]),
    ("Scudo", ["скудо", "scudo"]),
    # --- Citroen ---
    ("C3", ["c3", "с3"]),
    ("C4", ["c4", "с4"]),
    ("C5", ["c5", "с5"]),
    ("Berlingo", ["берлинго", "berlingo"]),
    ("C3 Aircross", ["c3 aircross", "с3 aircross"]),
    ("C5 Aircross", ["c5 aircross", "с5 aircross"]),
    ("Spacetourer", ["spacetourer", "спейстурер"]),
    ("Ami", ["ami", "ами"]),
    ("DS3 Crossback", ["ds3 crossback", "дс3 кроссбек"]),
    # --- Cadillac / Lincoln ---
    ("Escalade", ["эскалейд", "escalade"]),
    ("XT5", ["xt5", "хт5"]),
    ("XT6", ["xt6", "хт6"]),
    ("Navigator", ["навигатор", "navigator"]),
    ("Aviator", ["авиатор", "aviator"]),
    ("Corsair", ["корсар", "corsair"]),
    ("CT4", ["ct4", "кт4"]),
    ("CT5", ["ct5", "кт5"]),
    ("CT6", ["ct6", "кт6"]),
    ("XT4", ["xt4", "хт4"]),
    ("Lyriq", ["lyriq", "лирик", "лириq"]),
    ("Celestiq", ["celestiq", "селестик"]),
    ("CTS", ["cts", "ктс"]),
    ("ATS", ["ats", "атс"]),
    ("SRX", ["srx", "срх"]),
    ("Nautilus", ["nautilus", "наутилус"]),
    ("MKZ", ["mkz", "мкз"]),
    ("MKX", ["mkx", "мкх"]),
    ("MKT", ["mkt", "мкт"]),
    ("Continental", ["lincoln continental", "континенталь"]),
    ("MKC", ["mkc", "мкс"]),
    # --- Genesis ---
    ("G70", ["g70", "г70"]),
    ("G80", ["g80", "г80"]),
    ("G90", ["g90", "г90"]),
    ("GV70", ["gv70", "гв70"]),
    ("GV80", ["gv80", "гв80"]),
    # --- Daewoo / Ravon ---
    ("Matiz", ["матиз", "matiz"]),
    ("Nexia", ["нексия", "nexia"]),
    ("Gentra", ["гентра", "gentra"]),
    ("R2", ["r2", "р2"]),
    ("R4", ["r4", "р4"]),
    # --- Cupra ---
    ("Formentor", ["форментор", "formentor"]),
    ("Born", ["born", "борн"]),
    ("Ateca", ["атека", "ateca"]),
    ("Cupra Leon", ["cupra leon", "купра леон"]),
    ("Tavascan", ["tavascan", "таваскан"]),
    ("Terramar", ["terramar", "террамар"]),
    # --- MG ---
    ("ZS", ["zs", "зс"]),
    ("HS", ["hs", "хс"]),
    ("RX5", ["rx5", "рх5"]),
    # --- Tank ---
    ("300", ["tank 300", "300"]),
    ("500", ["tank 500", "500"]),
]

BRAND_CANONICAL: frozenset[str] = frozenset(name for name, _ in BRAND_ALIAS_GROUPS)
